language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.9.6

install:
  - pip install nose codecov
  - pip install -q Django==$DJANGO_VERSION

script: nosetests --with-coverage --cover-package=throttled_logger

after_success:
  - codecov
